### ISSUE TITLE
How to query table content from the debug session?

### ISSUE THREAD

**Issue by shkvoretz** [ng-galien/idea-plpgdebugger#101]
How do I attach to the db session and query tables? I can watch content of the variables fine, but how do I query tables tho?

**Comment by ng-galien** [comment]
Hi, you can try this method:
Affect the result of pg_export_snapshot() to a variable like it's described here 
 https://stackoverflow.com/questions/33066372/postgresql-connect-to-the-same-session-from-two-differnet-applications

But I really don't know if it works
