### ISSUE TITLE
DataGrip Plugin failed to start

### ISSUE THREAD

**Issue by chernia** [ng-galien/idea-plpgdebugger#102]
**Describe the bug**

**To Reproduce**
1. Start debugging a procedure 
2. IDE error occurred: 
1 of Exception in plugin PostgreSQL Debugger (222.3.3)

Run failed to start

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at net.plpgsql.ideadebugger.command.PlExecutor.createListener(PlExecutor.kt:111)
	at net.plpgsql.ideadebugger.run.PlProcess$InnerThread.run(PlProcess.kt:347)

**Expected behavior**
Debuggers starts as described.

**Screenshots**
<img width="429" alt="Screenshot 2023-05-09 at 19 56 44" src="https://github.com/ng-galien/idea-plpgdebugger/assets/46889914/60fe19f4-15d5-4d59-b0e0-5643b5a42bd1">

<img width="848" alt="Screenshot 2023-05-09 at 19 54 16" src="https://github.com/ng-galien/idea-plpgdebugger/assets/46889914/31dd35d4-4cdf-47e0-844b-b7e9e1cd9c6e">

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1  
 - Tool: DataGrip 2023.1.1

**Additional context**

**Comment by ng-galien** [comment]
Please check you can run pldbg_create_listener() on your database. you probably install the extension on a specific schema.

**Comment by chernia** [comment]
You are right. It was in a specific schema, though in search_path. Once in public all seems fine.
Thank you.
