### ISSUE TITLE
Disabled debug icon

### ISSUE THREAD

**Issue by neopaf** [ng-galien/idea-plpgdebugger#148]
thanks for your efforts!!

**Describe the bug**
Once I was able to start debugging.
After few IDE restarts I can not do that anymore -- my Debug button is disabled (grayed out).

**Screenshots**
 
<img width="354" alt="Снимок экрана 2023-09-18 в 16 24 14" src="https://github.com/ng-galien/idea-plpgdebugger/assets/4362564/3b5e2992-f5a4-446e-80aa-34731641a816">

**Additional context**

IDEA Plugin version 222.3.2

IntelliJ IDEA 2022.3.3 (Ultimate Edition) Build #IU-223.8836.41, built on March 10, 2023

PostgreSQL 13.9 (Debian 13.9-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by neopaf** [comment]
Workaround: reinstall the plugin.

**Comment by ng-galien** [comment]
I think reinstall is not necessary as all this logic is not persisted across IDE restarts. 
Did you check there was no debugger process in the task bar?
The debugger is intrusive for postgres has it preempt the session. You can try to kill the pid of the session if the IDE is not able to kill a dead session.

**Comment by neopaf** [comment]
I didn't check :(
Maybe, for slow-checkers like me do not disable debug button... but on click to it do a quick check and show relevant message that would set the user on a right thought track?
