### ISSUE TITLE
Wrong error message: complains about plpgsql missing, but should be pldbgapi

### ISSUE THREAD

**Issue by fatso83** [ng-galien/idea-plpgdebugger#153]
**Describe the bug**

If you spin up the Docker database and try to right click on the Debug procedure/function and run Debug, you will get a dialogue saying that you are missing the plpgsql extension. Installing it will do nothing, but installing the pldbgapi extension mentioned in the README will fix the issue. This sent me off in the wrong direction for two days.

**To Reproduce**
1. Create a function
2. Use the debug Docker image
3. Try to run a debug session before installing the pldbgapi extension

**Expected behavior**
An error saying I have not installed pldbgapi

**Screenshots**

<img width="369" alt="extension already exists" src="https://github.com/ng-galien/idea-plpgdebugger/assets/618076/9a3dafee-4f53-4cb4-bee5-cd8ee38fe81e">
<img width="716" alt="plpgsql missing" src="https://github.com/ng-galien/idea-plpgdebugger/assets/618076/ffff033b-2e0d-40a2-bb75-43ff0a7e2a4b">

**Desktop (please complete the following information):**
 - OS: macos
 - Version 14

**Comment by ng-galien** [comment]
Thank you for reporting the issue, it will be fixed soon.

**Comment by ng-galien** [comment]
Fix will be available in couple of days.
