### ISSUE TITLE
Plugin is not compatible with the current version of the Intellij IDEA IDE v233.*

### ISSUE THREAD

**Issue by htpaf** [ng-galien/idea-plpgdebugger#154]
**Is your feature request related to a problem? Please describe.**
The IDE gives the following error message:
`Plugin 'PostgreSQL Debugger' (version '232.0.3') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.241`

**Describe the solution you'd like**
A new version of Intellij IDEA is out and the plugin cannot be loaded.
`Build #IU-233.11799.241, built on December 2, 2023`
Please remove the version restriction or similar to make it possible to load the plugin assuming that is all that is really required.

**Describe alternatives you've considered**
The alternative is to downgrade used version of Intellij IDEA.

**Additional context**
N/A

**Comment by ng-galien** [comment]
Thanks for reporting, compatible release will be available in couple of days on market place, you can also find 233.0.1 in the releases page of this repo.
