### ISSUE TITLE
Detection support

### ISSUE THREAD

**Issue by ng-galien** [ng-galien/idea-plpgdebugger#19]
# Overview

Identify the target procedure

# Features

- [x] Document calling convention
- [x] Parse the call 
- [x] Handle procedure schema
- [x] Handle argument schema
- [x] Test the best candidate
- [x] Handle quotes
- [x] Create procedure for detection support
- [x] Provide two modes for detection, with internal API and Fail back with Queries

**Comment by ng-galien** [comment]
Related specific issue #13

**Comment by ng-galien** [comment]
Due to complexity of pg_proc, we have to build a stored procedure for that

**Comment by cvas71** [comment]
@ng-galien, ok!
