### ISSUE TITLE
Keyboard selection does not enable "Debug" button

### ISSUE THREAD

**Issue by ukolovda** [ng-galien/idea-plpgdebugger#22]
**Describe the bug**
If I select code from keyboard, the button `Debug` leaves disabled.

**To Reproduce**
1. Move editor cursor to start of expression
2. Press `Shift` and select some text
3. Button "Debug" can't enabled.

**Expected behavior**
Should be enabled button.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/1921594/150672755-8396777e-6b44-435b-957b-a8f85bae48f4.png)

(RubyMine 2021.3.1)

**Comment by ng-galien** [comment]
Not related to the plugin
