### ISSUE TITLE
Can We get some help making this work in DataGrip?

### ISSUE THREAD

**Issue by kirkw** [ng-galien/idea-plpgdebugger#226]
All of the examples are for IntelliJ.
I've installed it, I've enabled the debugger (I can debug a routine using 2 psql terminals).

But when I click on the Left Bug Icon (or the right click menu I get the same error message):

You must select only one valid query

Which I am doing.  But, again, I am using DataGrip.
It's like it is trying to open some other window or something, and failing.

But I noticed someone else wrote a comment about using it with DataGrip, and it seems to work for them.
Any Help is appreciated.
I would be glad to generate clean documentation for other DataGrip users once I get it working.  I have a small team with 5 other users that all would like to have this working.  So I will have to document it for my team.

**Comment by ng-galien** [comment]
Hi, 
As Database Tools is the same for Intellij or Datagrip the plugin should work as well for both platforms.
Did you select your query and use the debug button like in the screenshots? 
I need more information about your problems.
