### ISSUE TITLE
Could you support 2022.1 

### ISSUE THREAD

**Issue by helmus** [ng-galien/idea-plpgdebugger#44]
Please support latest version ( 2022.1 )  of intelij

**Comment by ng-galien** [comment]
@helmus because the plugin uses non public API I prefer to wait until it's released, thanks for you comprehension

**Comment by ng-galien** [comment]
Related to #47

**Comment by ng-galien** [comment]
@helmus 
At the moment Intellij 2021 does not start
![image](https://user-images.githubusercontent.com/33391039/161838984-bc01870f-240c-4aa6-9f67-27f6451ba908.png)

**Comment by helmus** [comment]
Are you saying the plugin is also broken in 2021 ?

**Comment by ng-galien** [comment]
2021 is fine on my side, you can try it with the latest release ( v213.1.1) with some improvments.
You can start debug routines or triggers from the Database tree.

**Comment by ng-galien** [comment]
@helmus the new version is on the go, will be available within 2 days on the marketplace or directly here
[v221.1.1](https://github.com/ng-galien/idea-plpgdebugger/releases/tag/v221.1.1)
