### ISSUE TITLE
Can't debug routines in schema other than `public` (PostgreSQL 14.1)

### ISSUE THREAD

**Issue by ukolovda** [ng-galien/idea-plpgdebugger#5]
**Describe the bug**
I see `Routine not found` error.

**To Reproduce**

```postgresql
create schema s_test;

create or replace function s_test.test_debug(p_text text, p_int integer DEFAULT 0) returns text
  language plpgsql
as
$$
BEGIN
  return 'DEBUG END';
end
$$;

SELECT s_test.test_debug('TEST', 0);
```
Try debug last row.

**Expected behavior**
Should debug routines in schemas

**Screenshots**
![изображение](https://user-images.githubusercontent.com/1921594/149653207-1730c757-6326-4a27-a88f-4cf567f21758.png)

**Comment by ukolovda** [comment]
PostgreSQL 14.1 (Docker-version)

**Comment by ng-galien** [comment]
Will be fixed in alpha1

**Comment by ng-galien** [comment]
Need your feedback to close it

**Comment by ukolovda** [comment]
Thank you!
Now it works fine.
