### ISSUE TITLE
Provide Docker image with enhanced debugger

### ISSUE THREAD

**Issue by ng-galien** [ng-galien/idea-plpgdebugger#52]
The legacy PostgreSQL debugger has some limitations as it only outputs a subset of variable.
It only outputs basic variables and arrays. Rows, records and structured type are discarded. 

Compile the modified debugger is not technically difficult but requires a Linux platform as it's too complicated on Windows.

We can provide a Docker image of the PostgreSQL with the enhanced debugger:

- Based on legacy image
- Compile the enhanced debugger against modified sources
- Install and configure it in shared libraries

**Comment by ng-galien** [comment]
# On Postgres image

## Install Postgres and debugger sources

> apt update && apt upgrade  

> apt install git build-essential libreadline-dev zlib1g-dev bison libkrb5-dev flex postgresql-server-dev-1X

> cd /usr/src/

> git clone https://github.com/postgres/postgres.git

> cd postgres  

> git checkout REL_1X_STABLE

> ./configure

> cd contrib

> git clone https://github.com/ng-galien/pldebugger.git

> cd pldebugger/

> git checkout print-vars

## Install debugger

> make clean && make USE_PGXS=1 && make USE_PGXS=1 install

## TODO

Change postgres.conf and add shared library

**Comment by tjlee** [comment]
>Change postgres.conf and add shared library

Do you mean this chunk? What value it should contain? 
`#shared_preload_libraries = ''		# (change requires restart)`

**Comment by tjlee** [comment]
There is no `print-vars` branch in this repo

**Comment by tjlee** [comment]
Also, not clear, why do you need to checkout postgresql repo? You can base image upon official image...

**Comment by ng-galien** [comment]
@tjlee We need the source tree to compile the debugger.

**Comment by ng-galien** [comment]
> >Change postgres.conf and add shared library
> 
> 
> 
> Do you mean this chunk? What value it should contain? 
> 
> `#shared_preload_libraries = ''		# (change requires restart)`
> 
> 

Yes, we have to change it with sed to do not maintain a configuration file per PostgreSQL version.

**Comment by tjlee** [comment]
>Yes, we have to change it with sed to do not maintain a configuration file per PostgreSQL version.

But what value should we provide?

**Comment by ng-galien** [comment]
> >Yes, we have to change it with sed to do not maintain a configuration file per PostgreSQL version.
> 
> 
> 
> But what value should we provide? 

The plugin library like described here

https://www.postgresonline.com/article_pfriendly/214.html

**Comment by tjlee** [comment]
Yes, you can use image tag to stick versions.

**Comment by ng-galien** [comment]
@tjlee The images are ready for PG14&13

> docker run -p 5514:5432 --name PG14-debug -e POSTGRES_PASSWORD=postgres -d galien0xffffff/postgres-debugger:14

https://hub.docker.com/repository/docker/galien0xffffff/postgres-debugger
