### ISSUE TITLE
Cannot debug function from database explorer due to missing extension plpgsql

### ISSUE THREAD

**Issue by stevenmccormack** [ng-galien/idea-plpgdebugger#59]
**Describe the bug**
When I try to debug a function by right clicking and selecting "Debug Routine" in the explorer I receive the following error:

![grafik](https://user-images.githubusercontent.com/61007020/166918492-901f7e9b-f57a-4315-bec8-1846f7988ffd.png)

**To Reproduce**
1. Create a schema and function to debug:
```pgsql
create schema if not exists test_schema;

create or replace function test_schema.debug_test() returns text as $$
begin
  return 'Test';
end;
$$ language plpgsql;
```
3. Richt click 'debug_test' in database explorer
4. Select 'Debug Routine'

**Expected behavior**
Function is debugged

**Desktop (please complete the following information):**
 - OS: Debian Linux Kernel 5.17.0-1-amd64
 - DataGrip 2022.1.1
 - PostgreSQL Debugger 221.1.2

**Additional context**
Debugging the following from a console window works as expected:
```pgsql
select test_schema.debug_test();
```

**Comment by ng-galien** [comment]
Did you install the debugger extension on your database?

>CREATE EXTENSION if not exists pldbgapi;

**Comment by stevenmccormack** [comment]
Yes, the extension is installed. Debugging works from a console window. The error only occurs when debugging a function from the context menu in database explorer.

Please find below the requested output:
| nspname | extname | extversion |
| :--- | :--- | :--- |
| pg\_catalog | plpgsql | 1.0 |
| public | pg\_trgm | 1.6 |
| public | uuid-ossp | 1.1 |
| public | pldbgapi | 1.1 |

**Comment by ng-galien** [comment]
@stevenmccormack 

Which pg version are you using? 
In the datasource config, check if the test_schema is introspected.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/33391039/166983697-4989ca3f-36bd-4d44-819e-f57bb2ac61f9.png">

**Comment by stevenmccormack** [comment]
Hi @ng-galien,
thanks for the update. Both schemas have been introspected. The server is running `DBMS: PostgreSQL (ver. 14.2 (Debian 14.2-1.pgdg110+1))
Case sensitivity: plain=lower, delimited=exact
Driver: PostgreSQL JDBC Driver (ver. 42.3.3, JDBC4.2)`. 
My IDE version is `Build #DB-221.5080.224, built on April 13, 2022`

**Comment by ng-galien** [comment]
Hi @stevenmccormack 

I've tried to reproduce the problem.

IDEA: Build #IU-221.5080.210, built on April 12, 2022
OS: Darwin MacBook-Pro 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64
PG: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

PG use my customized image
> docker run -p 5514:5432 --name PG14-debug -e POSTGRES_PASSWORD=postgres -d galien0xffffff/postgres-debugger:14

<img width="801" alt="image" src="https://user-images.githubusercontent.com/33391039/167249456-19fc995d-9571-47e0-9bac-8747c0d12a18.png">


I run the command

>CREATE EXTENSION IF NOT EXISTS pldbgapi;
CREATE SCHEMA IF NOT EXISTS test_schema;
CREATE OR REPLACE FUNCTION test_schema.debug_test() RETURNS TEXT AS
$$
BEGIN
    RETURN 'Test';
END;
$$ LANGUAGE plpgsql;

And the problem does not appears.
You can try to customize you search_path by setting a custom SQL command the plugin option

>SET SEARCH_PATH TO test_schema,public;

<img width="982" alt="image" src="https://user-images.githubusercontent.com/33391039/167249312-932eb804-4f87-47fc-92d3-a6a66badbce3.png">

**Comment by ng-galien** [comment]
@stevenmccormack 
I think this is fixed

**Comment by stevenmccormack** [comment]
Hi @ng-galien,

I just tried the new version and can confirm 221.1.3 fixed it for me.

Thanks!
