### ISSUE TITLE
Debugger only works once

### ISSUE THREAD

**Issue by gisborne** [ng-galien/idea-plpgdebugger#74]
Started a debugging session from the Database Explorer.

This worked once. The next time I invoked the same function, it just ran, no debugger.

M1 Mac, Postgres 14, IntelliJ

**Comment by ng-galien** [comment]
Hi @gisborne 

Can you test the  following:

Run first and puts a breakpoint anywhere.
Run again and check if it's reaching this breakpoint.

**Comment by gisborne** [comment]
That’s what I did that failed.

**Comment by ng-galien** [comment]
Thanks I'm working on a fix asap

**Comment by ng-galien** [comment]
Seems to be solved by mainly recompiling the plugin, it's available [here](https://github.com/ng-galien/idea-plpgdebugger/releases/tag/v222.0.4) for manual installation or within 2 days on the Marketplace.

**Comment by ghtropic** [comment]
Is it fixed only for Postgres 14 ?

Have the same issue.
Linux Ubuntu 22, Postgres 13 (docker image: galien0xffffff/postgres-debugger:13), PhpStorm 2022.3
Plugin 222.3.0

**Comment by ng-galien** [comment]
> Is it fixed only for Postgres 14 ?

On the Intellij side there is no differences against postgres version.   
If you can't run the debugger session twice you can check that your current user is able kill the previous session if it exists (check existing session on the database with PgAdmin).
If this session can't be terminated, the plugin will not run again.

```sql
      SELECT pid,
             application_name,
             usename,
             client_addr
      FROM pg_stat_activity
      WHERE application_name = 'idea_debugger'
      AND pid <> pg_backend_pid();
``` 

And 
```sql
SELECT pg_terminate_backend(pid);
```
