### ISSUE TITLE
Support json format for exploding values and outputs RECORD type in JSON

### ISSUE THREAD

**Issue by ng-galien** [ng-galien/idea-plpgdebugger#82]
JSON and JSONB variables outputs are just inlined and not exploded in the variable view.

For RECORD type, as it's returned as a ROW without type we can outputs it as JSONB.

@cvas71 what's your feelings about it?

**Comment by cvas71** [comment]
A good idea. I thought about it. But I don't know yet how to do it. I do not yet know the methods by which it could be done. It is possible that you will need to add something to the extension code.

**Comment by ng-galien** [comment]
I released it yesterday and waiting for your feedback 😉
As it implied pldebugger changes don't miss to pull the latest image.
I'm looking for your PR too

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cvas71** [comment]
Excellent! Installed plugin 222.2, compiled the plugin_debugger library. Everything is great. I would also like my changes (https://github.com/ng-galien/pldebugger/pull/4) that I made to be included in the build as well.

**Comment by ng-galien** [comment]
@cvas71 Your modifications are pushed to the pldebugger and dockers images 13 & 14 (branch print-vars)

Thanks again!

**Comment by cvas71** [comment]
I am very pleased that my participation in your project was useful.
