### ISSUE TITLE
Incorrect position in source method

### ISSUE THREAD

**Issue by cvas71** [ng-galien/idea-plpgdebugger#86]
If in a function, add a comment before DECLARE or, for example, a special command such as #variable_conflict use_variable.
When debugging, the cursor is set to a line lower than it should be.

**Comment by ng-galien** [comment]
Hi @cvas71 

The function source is returned by postgres and parsed by the built-in SQL support, is it possible to paste here a sample to reproduce the problem?

**Comment by cvas71** [comment]
I have made changes to your test case.

![image](https://user-images.githubusercontent.com/98530452/197189393-a9b823e6-d4d4-4203-8df3-2c0a280f948a.png)

![image](https://user-images.githubusercontent.com/98530452/197189432-d1902487-0fe8-4a79-aac5-e96077a18755.png)

**Comment by cvas71** [comment]
In pgAdmin, the cursor position is displayed on the correct line.
![image](https://user-images.githubusercontent.com/98530452/197189778-f9f7a23d-c6b5-4087-bc13-5e91f3d64428.png)
