### ISSUE TITLE
Only first char of variable of type char is displayed.

### ISSUE THREAD

**Issue by ghtropic** [ng-galien/idea-plpgdebugger#93]
Only first char of variable of type char is displayed.

Linux Ubuntu 22, Postgres 13 (docker image: galien0xffffff/postgres-debugger:13), PhpStorm 2022.3
Plugin 222.3.0

![2023-01-29_21-28](https://user-images.githubusercontent.com/9151824/215344632-f1d48733-724a-4328-a654-04441f9d254d.png)
![2023-01-29_21-34](https://user-images.githubusercontent.com/9151824/215344880-44025315-a89d-472d-9d2a-59142aab6704.png)

**Comment by ng-galien** [comment]
The modified C debugger implementation [uses TEXT or JSONB casting](https://github.com/ng-galien/pldebugger/blob/8e3122fee645a921d9a743f6e3cadbf681103e35/plpgsql_var.c#L7), I will check if char(3) returns a suitable string.  
If you do not need to see structured data in the debugger variable inspection you can use the legacy C debugger

**Comment by ng-galien** [comment]
@ghtropic 
Fixed in next release, will be available soon on the market place or it can be installed manually in the [release page ](https://github.com/ng-galien/idea-plpgdebugger/releases)

**Comment by ghtropic** [comment]
Thank you! 🙂
